
  - package-ecosystem: "gomod"
    directory: "/examples"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/tutorials"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all:
        patterns:
          - "*"
