name: Feature Request
description: Suggest a feature you miss.
type: feature
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
