name: coverage

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: stable
      go-version-file:
        required: false
        type: string
      working-directory:
        required: false
        type: string
      test-timeout:
        required: false
        type: string
        default: 5m
    secrets:
      gh_pat:
        required: false
      codecov_token:
        required: false

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmcli".insteadOf "https://github.com/charmcli"
        if: env.GH_PAT != null
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ inputs.go-version }}
          go-version-file: ${{ inputs.go-version-file }}
          cache: true
      - name: Download Go modules
        run: go mod download
        working-directory: ${{ inputs.working-directory }}
      - name: Test
        run: go test -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./... -timeout ${{ inputs.test-timeout }}
        working-directory: ${{ inputs.working-directory }}
      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          file: ./coverage.txt
          token: ${{ secrets.codecov_token }}
          working-directory: ${{ inputs.working-directory }}
