name: coverage

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: stable
      go-version-file:
        required: false
        type: string
      working-directory:
        required: false
        type: string
      test-timeout:
        required: false
        type: string
        default: 5m
    secrets:
      gh_pat:
        required: false
      codecov_token:
        required: false

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmcli".insteadOf "https://github.com/charmcli"
        if: env.GH_PAT != null
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ inputs.go-version }}
          go-version-file: ${{ inputs.go-version-file }}
          cache: true
      - name: Download Go modules
        run: go mod download
        working-directory: ${{ inputs.working-directory }}
      - name: Test
        run: go test -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./... -timeout ${{ inputs.test-timeout }}
        working-directory: ${{ inputs.working-directory }}
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          file: ./coverage.txt
          token: ${{ secrets.codecov_token }}
          working-directory: ${{ inputs.working-directory }}
