name: goreleaser

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: stable
      goreleaser_version:
        required: false
        type: string
        default: latest
      upload_artifact:
        required: false
        type: boolean
        default: true
      lfs:
        required: false
        type: boolean
        default: false
        description: Whether to download Git-LFS files
      macos_sign_entitlements:
        required: false
        type: string
        description: Path to entitlements file
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true
      gh_pat:
        required: true
      goreleaser_key:
        required: true
      aur_key:
        required: false
      fury_token:
        required: false
      nfpm_gpg_key:
        required: false
      nfpm_passphrase:
        required: false
      snapcraft_token:
        required: false
      twitter_consumer_key:
        required: false
      twitter_consumer_secret:
        required: false
      twitter_access_token:
        required: false
      twitter_access_token_secret:
        required: false
      mastodon_client_id:
        required: false
      mastodon_client_secret:
        required: false
      mastodon_access_token:
        required: false
      discord_webhook_id:
        required: false
      discord_webhook_token:
        required: false
      macos_sign_p12:
        required: false
      macos_sign_password:
        required: false
      macos_notary_key:
        required: false
      macos_notary_key_id:
        required: false
      macos_notary_issuer_id:
        required: false

jobs:
  release:
    if: ${{ !contains(github.repository, '-internal') }}
    runs-on:
      # Use our own large runners with more CPU and RAM for faster builds
      group: releasers
    permissions:
      contents: write
      id-token: write
      packages: write
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          lfs: ${{ inputs.lfs }}
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmcli".insteadOf "https://github.com/charmcli"
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
          check-latest: true
      - uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          github_access_token: ${{ secrets.gh_pat }}
      - run: nix profile install nixpkgs#nixfmt-rfc-style
      - uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
      - uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        name: ghcr.io login
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        name: docker.io login
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}
      - run: |
          echo "$NFPM_GPG_KEY" > ${{ runner.temp }}/gpg.key
        env:
          NFPM_GPG_KEY: ${{ secrets.nfpm_gpg_key }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      # - uses: samuelmeuli/action-snapcraft@fceeb3c308e76f3487e72ef608618de625fb7fe8 # v3.0.1
      - uses: goreleaser/goreleaser-action@1a80836c5c9d9e5755a25cb59ec6f45a3b5f41a8 # v7
        with:
          version: ${{ inputs.goreleaser_version }}
          distribution: goreleaser-pro
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.gh_pat }}
          GORELEASER_KEY: ${{ secrets.goreleaser_key }}
          AUR_KEY: ${{ secrets.aur_key }}
          FURY_TOKEN: ${{ secrets.fury_token }}
          GPG_KEY_PATH: ${{ runner.temp }}/gpg.key
          NFPM_DEFAULT_PASSPHRASE: ${{ secrets.nfpm_passphrase }}
          TWITTER_CONSUMER_KEY: ${{ secrets.twitter_consumer_key }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.twitter_consumer_secret }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.twitter_access_token }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.twitter_access_token_secret }}
          MASTODON_CLIENT_ID: ${{ secrets.mastodon_client_id }}
          MASTODON_CLIENT_SECRET: ${{ secrets.mastodon_client_secret }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.mastodon_access_token }}
          DISCORD_WEBHOOK_ID: ${{ secrets.discord_webhook_id }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.discord_webhook_token }}
          MACOS_SIGN_P12: ${{ secrets.macos_sign_p12 }}
          MACOS_SIGN_PASSWORD: ${{ secrets.macos_sign_password }}
          MACOS_SIGN_ENTITLEMENTS: ${{ inputs.macos_sign_entitlements }}
          MACOS_NOTARY_ISSUER_ID: ${{ secrets.macos_notary_issuer_id }}
          MACOS_NOTARY_KEY_ID: ${{ secrets.macos_notary_key_id }}
          MACOS_NOTARY_KEY: ${{ secrets.macos_notary_key }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}
          POSTHOG_KEY: ${{ secrets.posthog_key }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ inputs.upload_artifact == true && always() }}
        with:
          retention-days: 30
          name: dist
          path: |
            dist

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
