name: govulncheck

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: stable
      cache:
        required: false
        type: boolean
        default: true
    secrets:
      gh_pat:
        required: false

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
        if: env.GH_PAT != null
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
          cache: ${{ inputs.cache }}
      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...