name: lint
on:
  workflow_call:

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/meta
          path: ${{ github.repository_owner }}/meta
      - run: |
          pwd
          tree
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ${{ github.repository }}
          # Optional: golangci-lint command line arguments.
          args: |
            --config="${{ github.workspace }}/${{ github.repository_owner }}/meta/golangci.yml"
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

  lint-soft:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/meta
          path: ${{ github.repository_owner }}/meta
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ${{ github.repository }}
          # Optional: golangci-lint command line arguments.
          args: |
            --config="${{ github.workspace }}/${{ github.repository_owner }}/meta/golangci-soft.yml" \
            --issues-exit-code=0
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
