name: lint
on:
  workflow_call:
    inputs:
      directory:
        type: string
        required: false
        description: Path to the directory to run golangci-lint in.
      golangci_path:
        type: string
        required: false
        description: Path to golangci.yml
      golangci_version:
        type: string
        required: false
        description: Version of golangci-lint to use.
      timeout:
        type: string
        required: false
        description: Timeout for golangci-lint.

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # By default, the GitHub Action on Windows uses `core.autocrlf=true`.
      # LF is converted to CRLF, this produces reports from formatters (gofmt/gofumpt/etc.).
      - run: "git config --global core.autocrlf input"
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: ${{ github.repository }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: charmbracelet/meta
          path: charmbracelet/meta
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          working-directory: ${{ github.repository }}
          args: |
            --config="${{ inputs.golangci_path || format('{0}/{1}/meta/golangci.yml', github.workspace, github.repository_owner) }}" --timeout=${{ inputs.timeout || '5m' }} ${{ inputs.directory }}
          version: ${{ inputs.golangci_version || 'v2.4' }}
