name: nightly

on:
  workflow_call:
    inputs:
      upload_artifacts:
        required: false
        type: boolean
        default: true
      go_version:
        required: false
        type: string
        default: ^1
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true
      goreleaser_key:
        required: true
      gh_pat:
        required: false
      fury_token:
        required: false

jobs:
  nightly:
    runs-on: ubuntu-latest
    # dependabot-created PRs cant see any secrets, so this workflow wont work anyway https://github.com/dependabot/dependabot-core/issues/3253
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
      id-token: write
      packages: write
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
      if: env.GH_PAT != null
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}
        cache: true
    - uses: sigstore/cosign-installer@v2.8.1
    - uses: anchore/sbom-action/download-syft@v0.13.0
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      name: ghcr.io login
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@v2
      name: docker.io login
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_token }}
    - uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        distribution: goreleaser-pro
        args: release --rm-dist --nightly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GORELEASER_KEY: ${{ secrets.goreleaser_key }}
        FURY_TOKEN: ${{ secrets.fury_token }}

    - uses: actions/upload-artifact@v3
      if: inputs.upload_artifacts == true
      with:
        name: Linux (x86_64)
        path: |
          dist/*_linux_amd64/*
          LICENSE
          README.md

    - uses: actions/upload-artifact@v3
      if: inputs.upload_artifacts == true
      with:
        name: Linux (arm64)
        path: |
          dist/*_linux_arm64/*
          LICENSE
          README.md

    - uses: actions/upload-artifact@v3
      if: inputs.upload_artifacts == true
      with:
        name: MacOS (x86_64)
        path: |
          dist/*_darwin_amd64/*
          LICENSE
          README.md

    - uses: actions/upload-artifact@v3
      if: inputs.upload_artifacts == true
      with:
        name: MacOS (arm64)
        path: |
          dist/*_darwin_arm64/*
          LICENSE
          README.md

    - uses: actions/upload-artifact@v3
      if: inputs.upload_artifacts == true
      with:
        name: Windows (x86_64)
        path: |
          dist/*_windows_amd64/*
          LICENSE
          README.md
