name: nightly

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: stable
      lfs:
        required: false
        type: boolean
        default: false
        description: Whether to download Git-LFS files
    secrets:
      docker_username:
        required: false
      docker_token:
        required: false
      goreleaser_key:
        required: true
      gh_pat:
        required: false
      fury_token:
        required: false
      macos_sign_p12:
        required: false
      macos_sign_password:
        required: false
      macos_notary_key:
        required: false
      macos_notary_key_id:
        required: false
      macos_notary_issuer_id:
        required: false

jobs:
  nightly:
    runs-on: ubuntu-latest
    # dependabot-created PRs cant see any secrets, so this workflow wont work anyway https://github.com/dependabot/dependabot-core/issues/3253
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
      id-token: write
      packages: write
      attestations: write
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GH_PAT: ${{ secrets.gh_pat }}
      DOCKER_ENABLED: ${{ secrets.docker_username != '' }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          lfs: ${{ inputs.lfs }}
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmcli".insteadOf "https://github.com/charmcli"
        if: env.GH_PAT != null
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
          check-latest: true
      - uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62
      - uses: anchore/sbom-action/download-syft@v0.20.5
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
        if: env.DOCKER_ENABLED == 'true'
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
        if: env.DOCKER_ENABLED == 'true'
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        name: ghcr.io login
        if: env.DOCKER_ENABLED == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        name: docker.io login
        if: env.DOCKER_ENABLED == 'true'
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}
      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a
        with:
          version: latest
          distribution: goreleaser-pro
          args: release --clean --nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.goreleaser_key }}
          FURY_TOKEN: ${{ secrets.fury_token }}
          MACOS_SIGN_P12: ${{ secrets.macos_sign_p12 }}
          MACOS_SIGN_PASSWORD: ${{ secrets.macos_sign_password }}
          MACOS_NOTARY_ISSUER_ID: ${{ secrets.macos_notary_issuer_id }}
          MACOS_NOTARY_KEY_ID: ${{ secrets.macos_notary_key_id }}
          MACOS_NOTARY_KEY: ${{ secrets.macos_notary_key }}
      - uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a
        with:
          subject-checksums: ./dist/checksums.txt
      - uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a
        if: startsWith(github.ref, 'refs/tags/v') # snapshots won't push docker images
        with:
          subject-checksums: ./dist/digests.txt
