name: nightly

on:
  workflow_call:
    inputs:
      upload_artifacts:
        required: false
        type: boolean
        default: true
      upload_artifact:
        required: false
        type: boolean
        default: true
      go_version:
        required: false
        type: string
        default: stable
      lfs:
        required: false
        type: boolean
        default: false
        description: Whether to download Git-LFS files
      gcp_enabled:
        required: false
        type: boolean
        default: false
        description: Authenticate to GCP and configure Docker for Artifact Registry
    secrets:
      docker_username:
        required: false
      docker_token:
        required: false
      goreleaser_key:
        required: true
      gh_pat:
        required: false
      fury_token:
        required: false
      gcp_wif_provider:
        required: false
      gcp_service_account:
        required: false
      macos_sign_p12:
        required: false
      macos_sign_password:
        required: false
      macos_notary_key:
        required: false
      macos_notary_key_id:
        required: false
      macos_notary_issuer_id:
        required: false

jobs:
  nightly:
    runs-on:
      # Use our own large runners with more CPU and RAM for faster builds
      group: releasers
    # dependabot-created PRs cant see any secrets, so this workflow wont work anyway https://github.com/dependabot/dependabot-core/issues/3253
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
      id-token: write
      packages: write
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GH_PAT: ${{ secrets.gh_pat }}
      DOCKER_ENABLED: ${{ secrets.docker_username != '' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          lfs: ${{ inputs.lfs }}
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmcli".insteadOf "https://github.com/charmcli"
        if: env.GH_PAT != null
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
          check-latest: true
      - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      - uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
      - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
        if: env.DOCKER_ENABLED == 'true'
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        if: env.DOCKER_ENABLED == 'true'
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        name: ghcr.io login
        if: env.DOCKER_ENABLED == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        name: docker.io login
        if: env.DOCKER_ENABLED == 'true'
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        name: gcp auth
        if: ${{ inputs.gcp_enabled }}
        with:
          workload_identity_provider: ${{ secrets.gcp_wif_provider }}
          service_account: ${{ secrets.gcp_service_account }}
      - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
        name: setup gcloud
        if: ${{ inputs.gcp_enabled }}
      - run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet
        name: configure docker for artifact registry
        if: ${{ inputs.gcp_enabled }}
      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7
        with:
          version: latest
          distribution: goreleaser-pro
          args: release --clean --nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.goreleaser_key }}
          FURY_TOKEN: ${{ secrets.fury_token }}
          MACOS_SIGN_P12: ${{ secrets.macos_sign_p12 }}
          MACOS_SIGN_PASSWORD: ${{ secrets.macos_sign_password }}
          MACOS_NOTARY_ISSUER_ID: ${{ secrets.macos_notary_issuer_id }}
          MACOS_NOTARY_KEY_ID: ${{ secrets.macos_notary_key_id }}
          MACOS_NOTARY_KEY: ${{ secrets.macos_notary_key }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ inputs.upload_artifact == true && always() }}
        with:
          retention-days: 30
          name: dist
          path: |
            dist
