name: ruleguard

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: stable
      cache:
        required: false
        type: boolean
        default: true
      args:
        required: false
        type: string
        default: ""
      run:
        required: false
        type: string
    secrets:
      gh_pat:
        required: false

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.gh_pat }}
      RUN: ${{ inputs.run }}
    steps:
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmcli".insteadOf "https://github.com/charmcli"
        if: env.GH_PAT != null
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: dgryski/semgrep-go
          path: rules
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: ${{ inputs.cache }}
      - run: ${{ inputs.run }}
        if: env.RUN != null
      - name: ruleguard
        run: |
          # needs to be outside of the workspace for some reason
          mv rules ../
          go install github.com/quasilyte/go-ruleguard/cmd/ruleguard@master
          go get -u github.com/quasilyte/go-ruleguard/dsl@master
          ruleguard -c=0 -rules ../rules/ruleguard.rules.go ${{ inputs.args }} ./...
