name: semgrep

on:
  workflow_call:
    secrets:
      gh_pat:
        required: false

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    env:
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmcli".insteadOf "https://github.com/charmcli"
        if: env.GH_PAT != null
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: dgryski/semgrep-go
          path: rules
      - name: semgrep
        run: semgrep scan --error --enable-nosem -f ./rules .
