name: snapshot

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: ^1
      upload_artifact:
        required: false
        type: boolean
        default: true
    secrets:
      goreleaser_key:
        required: true
      gh_pat:
        required: false

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmbracelet".insteadOf "https://github.com/charmbracelet"
          git config --global url."https://${{ secrets.gh_pat }}@github.com/charmcli".insteadOf "https://github.com/charmcli"
        if: env.GH_PAT != null
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
          check-latest: true
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - run: sudo snap install snapcraft --classic
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        with:
          version: latest
          distribution: goreleaser-pro
          args: release --clean --snapshot --skip=sign,sbom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ inputs.upload_artifact == true && always() }}
        with:
          retention-days: 7
          name: dist
          path: |
            dist
