name: soft-serve

on:
  workflow_call:
    inputs:
      server:
        type: string
        default: "git.charm.sh"
        required: false
    secrets:
      ssh-key:
        required: true

jobs:
  soft-serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Push to Soft-Serve
        uses: charmbracelet/soft-serve-action@587fa24471792be19add5909e336ede12edad8cc # v1.0.0
        with:
          server: "${{ inputs.server }}"
          ssh-key: "${{ secrets.ssh-key }}"
          mirror: "true"
